apiVersion: cloudnativetoolkit.dev/v2
kind: Catalog
modules: []
boms:
  - name: 105-ibm-vpc-openshift
    displayName: IBM Simple VPC OpenShift
    description: IBM VPC and public Red Hat OpenShift server
    metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/105-ibm-vpc-openshift/latest.yaml
    tags:
      - ibm
      - openshift
      - vpc
      - public
    category: infrastructure
    type: bom
    cloudProvider: ibm
    versions:
      - version: v1.0.0
        metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/105-ibm-vpc-openshift/v1.0.0.yaml
  - name: 200-openshift-gitops
    displayName: OpenShift GitOps Bootstrap
    description: Provisions OpenShift GitOps (ArgoCD) into an existing cluster and bootstraps it to a gitops repository
    metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/200-openshift-gitops/latest.yaml
    tags:
      - openshift
      - gitops
      - bootstrap
    category: platform
    type: bom
    cloudProvider: ibm
    versions:
      - version: v1.0.0
        metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/200-openshift-gitops/v1.0.0.yaml
  - name: 210-ibm-odf-storage
    displayName: IBM - ODF Cluster Storage
    description: Installs OpenShift Data Foundation in an IBM cluster
    metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/210-ibm-odf-storage/latest.yaml
    tags:
      - odf
      - ibm
      - storage
    category: storage
    type: bom
    cloudProvider: ibm
    versions:
      - version: v1.0.0
        metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/210-ibm-odf-storage/v1.0.0.yaml
  - name: 210-ibm-portworx-storage
    displayName: IBM - Portworx Cluster Storage
    description: Installs Portworx in an IBM cluster
    metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/210-ibm-portworx-storage/latest.yaml
    tags:
      - portworx
      - ibm
      - storage
    category: storage
    type: bom
    cloudProvider: ibm
    versions:
      - version: v1.0.0
        metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/210-ibm-portworx-storage/v1.0.0.yaml
  - name: 220-dev-tools
    displayName: OpenShift development tools
    description: Provisions development tools in an OpenShift cluster
    metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/220-dev-tools/latest.yaml
    tags:
      - multi-cloud
      - dev tools
      - software
    category: software
    type: bom
    versions:
      - version: v1.0.0
        metadataUrl: https://cloud-native-toolkit.github.io/automation-solutions/boms/infrastructure/ibmcloud/220-dev-tools/v1.0.0.yaml
