apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: existing-cluster
spec:
  modules:
    - name: ibm-ocp-vpc
      dependencies:
        - name: subnets
          optional: true
        - name: cos
          optional: true
        - name: vpc
          optional: true
      variables:
        - name: exists
          value: true
        - name: name
          required: true
        - name: vpc_subnet_count
          value: 0
        - name: vpc_subnets
          value: "[]"
        - name: cos_id
          value: ""
        - name: vpc_name
          value: ""
        - name: login
          value: true
    - name: ocp-login
    - name: openshift-cicd
    - name: console-link-job
    - name: cluster-config
      alias: config
    - name: ibm-portworx
      dependencies:
        - name: ibm-ocp-vpc
      variables:
        - name: provision
          value: false
  variables:
    - name: config_banner_text