apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-ibm-portworx-storage
  labels:
    type: infrastructure
    platform: ibm
    code: '210'
  annotations:
    displayName: IBM - Portworx Cluster Storage
    description: Installs Portworx in an IBM cluster
spec:
  modules:
    - name: gitops-ibm-portworx
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
    - name: gitops-ibm-portworx
