apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: gitops-telco-cloud-cp4ba
  labels:
    code: '500'
  annotations:
    displayName: Telco Core
    description: Telco Core on OpenShift
spec:
  # assumes cluster already exists, is this enough for bootstrapping gitops?
  modules:

    # Login into IBM Cloud Clusters setup GitOps
    - name: ocp-login
    - name: gitops-repo
    - name: gitops-bootstrap

    # Cloud Pak Base
    - name: gitops-cp-catalogs
    - name: gitops-cp-platform-navigator

    # Cloud Pak Automation
    - name: gitops-cp4ba-operator




